### ISSUE TITLE
request: disable counter

### ISSUE THREAD

**Issue by dryodryo** [audioscavenger/save-image-extended-comfyui#19]
Hi,

Thanks for such a fantastic node, it brings usability to ComfyUI in terms of asset management.

My one request is to be able to turn off the counter entirely. I'm already naming generated files with date and time stamps. The counter is just unnecessary for me unless I'm working with image sequences.

I tried setting "counter_digits" to zero, but this broke the node so that it did not function at all.

Thanks again!!

**Comment by aaronnewsome** [comment]
I've switched to using this node since the other save image with metadata node no longer works with the latest comfyui.

This node has no way to turn off the counter. Setting counter digits to zero causes the workflow to fail.

If anyone knows of a way to turn off the counter, please advise. Or if you know of a node that can save PNG images with the workflow embedded as metadata, but doesn't use a counter for filenames, that would be equally welcome.

If you're wondering why I don't need counter digits, my API call uses unique file names in the call, the counter digits will require me to rework the logic.

**Comment by stormwulfren** [comment]
+1 for this.

I also use self-discriminating identifiers for filenames, and the ID only gets in the way. Suggest adding "counter_position = none" to the list of valid counter positions, presence of which disables the feature.

**Comment by audioscavenger** [comment]
Your dreams are now == True

set **counter_digits = 0** to disable it
