### ISSUE TITLE
Checkpoints in folders, when applied to filename, create subfolders when saving

### ISSUE THREAD

**Issue by ManOrMonster** [audioscavenger/save-image-extended-comfyui#7]
As you can see below, my checkpoints are in folders. Since ckpt_name grabs the entire name, including the path, it creates subfolders.
 
![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/48d5d7ed-3c1b-42e2-9a75-d274665d0670)

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/01340198-6fb3-4f98-8070-2a862a05170d)

Also, for some reason, it creates the file first then the subfolder in this case. It seems like it should have instead been:

```
FaceGen
└─ 2024-05-24
   └─ FaceGen-SDXL
      └─ .photo
         └─ sdxlHK_v09-0004.jpg
```

**Comment by audioscavenger** [comment]
it's all perfectly normal: 
* folder is FaceGen / %F
* then FaceGen-[ckpt_name].jpg
since ckpt_name is SDXL/.photo/sdxlHKwhatnot then that's exactly what you have

fixing this is easy, but then what do YOU want? some people like me want a subfolder because I place SDXL in subfolders myself. Therefore I have extra subfolders when using ckpt_name for SDXL only.
If you want no subfolders, then do you want all the path with separators instead? which separators? or just the filename.safetensors?
I am wary of modifying this part, as Comfy does exactly what it is supposed to: return a subpath/ckpt_name

**Comment by ManOrMonster** [comment]
I just want the checkpoint name in the file. I don't want any subfolders I don't specify explicitly.

So if the checkpoint is `SDXL\.photo\sdxlHK_v09.safetensors` I want the name added to the file to be `sdxlHK_v09`, or put in regex form, `.*\\(.+)\..+`.

My current solution is to use the WAS checkpoint loader and pass the name_string output to filename_keys in your node. Which is ironic since I originally got your node because the WAS image save node is broken after a recent update and takes like 5 times longer to save images.

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/2e0fca67-cf16-494b-af65-5a38a077dd67)

In any case, I have a solution. Do your node how you wanna! I'm just replacing my WAS save nodes in my workflows with yours becasue they work better. Good timing with this release BTW.

**Comment by audioscavenger** [comment]
hmmmm you may be right after all. if you really want subfolders for such and such model, you just have to add them yourself in the text zone. It makes sense, i guess.
should I submit a poll before modifying this? or since there are like only 10 users, should i not care and go ahead?
this modification will also affect controlnets

**Comment by ManOrMonster** [comment]
I don't see any reason why these can't both be accomplished: `ckpt_name` does the obivous thing and only grabs the name, and then add `ckpt_path` so people can add the path if they want. Same thing with ControlNet or anything else that would have a folder path.

**Comment by audioscavenger** [comment]
cktp_path!!! you just solved it, thanks

**Comment by audioscavenger** [comment]
release 2.73 address ckpt_path and control_net_path

**Comment by ManOrMonster** [comment]
Doesn't seem to have changed anything except for now putting the delimiter as a prefix to the foldername_keys. At least the folder order is correct this time. Also note that the delimiter was not used in "FaceGenSDXL";  it should have been "FaceGen_SDXL", unless the delimiter is no longer applied to file name?

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/03e1b4dc-8cb4-47f4-9784-4df9c597920d)

With `ckpt_name`:

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/d1980c8c-f2e4-4213-9bc8-acee7687af17)

Also, `ckpt_path` only creates the first folder(s), then names the file the final folder name.

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/95794470-0aeb-4639-854b-69d315b6d127)

And then `ckpt_path,ckpt_name` does this:

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/3925151/686f2f75-261a-445c-8212-d6cc5b2f9ffa)
